project:
  type: website
  resources:
    - CNAME 
toc: true
website:
  favicon: favicon.png
  title: "UndefinedVoidNull"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/UndefinedVoidNull/UndefinedVoidNull.github.io 
format:
  html:
    theme:
      - cosmo
    css: styles.css
editor:
  render-on-save: true