project:
  type: website

website:
  title: "Shigure Chizuru"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/UndefinedVoidNull/UndefinedVoidNull.github.io
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

