---
title: "Calc3 Notes"
date: "2025-01-10"
categories: [Math]
toc: true
format: html
---

# Vector Operations

$$
\begin{align*}
&\vec{u} =< u_1 ,u_2 ,u_3> \\
&\vec{v} =< v_1 ,v_2 ,\ v_3> \\
&|\vec{u} |=\sqrt{u_1^2 +u_2^2 +u_3^2}\\
&\hat{u} =\frac{\vec{u}}{|\vec{u}|}\\
&\vec{u} +\vec{v} =< u_{1} +v_{1} ,u_{2} +v_{2} ,u_{3} +v_{3}  >\\
&\vec{u} -\vec{v} =\vec{u} +( -\vec{v}) =< u_{1} -v_{1} ,u_{2} -v_{2} ,u_{3} -v_{3}  >\\
&\end{align*}
$$


# Dot Product (Evaluate works, Perp test)
$$
\begin{align*}
\vec{u} \cdotp \vec{v} 
&=|\vec{u} |\ |\vec{v} |\ cos( \theta ) \\
&=u_{1} v_{1} +u_{2} v_{2} +u_{3} v_{3} \ ( Cosine\ Rule)
\end{align*}
$$

# Cross Product 
Generate a vector perp to both two vectors, Parallel test, Evaluate Area

$$
\vec{u} \times \vec{v} =\ \begin{vmatrix}
\hat{i} & \hat{j} & \hat{k}\\
u_{1} & u_{2} & u_{3}\\
v_{1} & v_{2} & v_{3}
\end{vmatrix}\\
$$

$$
\begin{align*}
|\vec{u} \times \vec{v} |
&=|\vec{u} |\ |\vec{v} |\ sin( \theta )\\
&=\text{Area\ of\ Parallelogram}\\
&=\text{2 Times Area of Triangle}
\end{align*}
$$

## Box Product

## Projection and Scalar Projection
$$
\begin{aligned}
&Proj_{\vec{u}}\vec{v}=|\vec{v}|cos(\theta)\widehat{u}=|\vec{v}|\frac{\vec{u}\cdot\vec{v}}{|\vec{u}||\vec{v}|}\frac{\vec{u}}{|\vec{u}|}=\frac{\vec{u}\cdot\vec{v}}{|\vec{u}|^2}\vec{u}\\

&Scal_{\vec{u}}\vec{v}=|\vec{v}|\cos(\theta)=|\vec{v}|\frac{\vec{u}\cdot\vec{v}}{|\vec{u}||\vec{v}|}=\frac{\vec{u}\cdot\vec{v}}{|\vec{u}|}\\

&|Proj_{\vec{u}}\vec{v}|(maginititude)=|Scal_{\vec{u}}\vec{v}| (absvalue)
\end{aligned}
$$



# Line, Plane, Curve and Surface Equations
## Plane
$$
\begin{align*}
&\vec{n} \ =\ < a,b,c >\ ( normal\ vector) ,\ P=( x_{0} ,y_{0} ,z_{0}) ,\ Q=( x,y,z)\\
&\overrightarrow{PQ} \ =\ < x-x_{0} ,y-y_{0} ,\ z-z_{0}  >\ ( a\ vector\ in\ the\ plane)\\
&\vec{n} \cdotp \overrightarrow{PQ} =0\ ( orthognal)\\
&\Longrightarrow Dot-Normal\ Form:\ a( x-x_{0}) +b( y-y_{0}) +c( z-z_{0}) =0\ \\
&\Longrightarrow General\ Form:\ ax+by+cz=d\ ( d\ is\ a\ constant) \ \\
\end{align*}
$$

## Line
Take a line as the intersection of two planes ( general form)
$$
\begin{cases}
a_{1} x+b_{1} y+c_{1} z+d_{1} =0\\
a_{1} x+b_{1} y+c_{1} z+d_{1} =0
\end{cases}
$$

## Parameterization of line (dot-direction form)
$$
\vec{v} = < a,b,c > \text{(parallel to the line)}\\
r( t) =\ < x_{0} +at,\ y_{0} +bt,\ z_{0} +ct >
$$

### Surface

Explicit Form: $z=f( x,y)$
Implicit Form: $F(x,y,z)=0$
$\vec{r}( t) =\, < x( u,v) ,y( u,v) ,z( u,v)>$

### Curve
See curve as the intersection of two surfaces
$$
\begin{align*}
\begin{cases}
F( x,y,z) =0\\
G( x,y,z) =0
\end{cases}\\
\vec{r}( t) =\, < x(t) ,y(t) ,z(t)>
\end{align*}
$$

# Arc Length; (Unit) Tangent Vector, (Unit) Normal Vector, Binormal Vector; Curvature and Torsion

Arc Length: 
$s= \int _{a}^{t} |\vec{r} '( t) |\ dt=\int _{a}^{b} |\vec{r} '( t) |\ dt$

Unit Tangent Vector: 
$\vec{T}( t) =\frac{\vec{r} '( t)}{|\vec{r} '( t) |}$

Unit Normal Vector:
$\vec{N}( t) =\frac{\vec{T} '( t)}{|\vec{T} '( t) |}$
Unit Binormal Vector: $\vec{B}( t) =\vec{T} \times \vec{N}$


Curvature: 
$\kappa =\left| \frac{d\vec{T}}{ds}\right|$

Torsion: 
$$
\begin{align*}
&\frac{d\vec{B}}{ds} =\frac{d(\vec{T} \times \overrightarrow{N)}}{ds}\\
&=\frac{d\vec{T}}{ds} \times \vec{N} +\vec{T} \times \frac{d\vec{N}}{ds}\\
&=\ \kappa \vec{N} \times \vec{N} +\vec{T} \times \frac{d\vec{N}}{ds} \ \ by\ \vec{N} =\frac{\frac{d\vec{T}}{ds}}{|\frac{d\vec{T}}{ds} |} =\frac{1}{\kappa }\frac{d\vec{T}}{ds} \Longrightarrow \frac{d\vec{T}}{ds} \\
&=\kappa \vec{N}\\
&=\vec{T} \times \frac{d\vec{N}}{ds} \ \ by\ \kappa \vec{N} \times \vec{N} =0\ ( parallel)\\
&\Longrightarrow \frac{d\vec{B}}{ds} =\vec{T} \times \frac{d\vec{N}}{ds}\\
&\Longrightarrow \\
&( 1) \ \frac{d\vec{B}}{ds} \perp \vec{T} \ by\ cross\ product\\
&( 2) \ \frac{d\vec{B}}{ds} \perp \vec{B} \ by\ |\vec{B} |=1( constant) \Longrightarrow \vec{B} '\cdotp \vec{B} =0\ like\ tangent\ line\ of\ circle\perp radius\\
&\Longrightarrow \frac{d\vec{B}}{ds} //\ \vec{T} \times \vec{B}\\
&\Longrightarrow \frac{d\vec{B}}{ds} //\ \vec{N} \ \ {\displaystyle by\ \ \vec{T} \times \vec{B} \ //\ \vec{N}}\\
&\Longrightarrow \frac{d\vec{B}}{ds} =-\tau \vec{N} \ ( negative\ by\ convention)\\
&\Longrightarrow \ -\frac{d\vec{B}}{ds} \cdotp \vec{N} =\tau \vec{N} \cdotp \vec{N}\\
&\Longrightarrow \tau =\ -\frac{d\vec{B}}{ds} \cdotp \vec{N} \ \ by\ \vec{N} \cdotp \vec{N} \ =1\\
&\Longrightarrow |\tau |=\left| -\frac{d\vec{B}}{ds} \cdotp \vec{N}\right| =\left| \frac{d\vec{B}}{ds}\right| |\vec{N} |\ cos( \theta ) \ \xRightarrow[|\vec{N} |=1]{\theta =0}\left| \frac{d\vec{B}}{ds}\right| \\
\end{align*}
$$
We call $\kappa$ curvature, $\tau$ torsion.

# Partial Derivative, Chain Rule, Level Curve, Gradient

Crtical Points, Local Min/Max (Point), Saddle Point, Abs Min/Max, Lagrange Multiplier Crtical Points: 
$\ f_{x} =f_{y} =0\ or\ f_{x} \ DNE\ \ or\ f_{y} \ DNE$

# Vector Field, Line Integral, Surface Integral

## Potential Functions and Conservative
If exist function $\phi$  such that $\vec{F}  = \nabla \phi$ , 
we say function $\vec{F}$  is conservative, and 
call $\phi$  the potential function  of gradient vector field  $\vec{F}$

Conservative Discriminator
$$
\vec{F} =\, < f,\ g,\ h >,
$$
If $f_{y} =g_{x}$  and $f_{z} =h_{x}$  and $ g_{z} =h_{y}$,
then vector field $vec{F}$  is conservative

Fundamental Thm of Line Integral
If $\vec{F} = < f, g, h >$ is conservative, then
Circulation=$\oint _{a}^{b}\vec{F} \cdotp \vec{T} \ ds=\phi ( b) -\phi ( a)\\$


Definition of $\nabla$  Operator
$$\nabla \ :=\ < \frac{\partial \ }{\partial x} ,\ \frac{\partial \ }{\partial y} ,\ \frac{\partial \ }{\partial z}  >\\$$



Definition of Curl and Divergence
Curl($\vec{F}$) = $\nabla \times \vec{F}$
Divergence($\vec{F}$) =$\nabla \cdotp \vec{F}$



Green's Thm ( special case of Stoke's Thm,when the surface is flat)

Circulation= 
$$\oint _{C}\vec{F} \cdotp \vec{T} \ ds=\iint _{R} Curl\ \vec{F} \ dA\ \ ( Curl\ Form)\\$$

Flux=
$$
\oint _{C}\vec{F} \cdotp \vec{N} \ ds\ =\iint _{R} Divergence\ \vec{F} \ dA\ ( Divergence\ Form)\\
$$

## Stoke's Thm
$$
\begin{align*}
&\oint _{C}\vec{F} \cdotp \vec{T} \ ds\ ( circulation\ across\ boundary)\\
&=\iint _{S} Curl(\vec{F}) \cdotp \vec{N} \ dA\ ( surface\ intergal)\\
&=\iint _{S} Curl(\vec{F}) \cdotp \left(\overrightarrow{t_{u}} \times \overrightarrow{t_{v}}\right) \ dA\\
\end{align*}
$$

## Divergence Thm

$$
\oiint_S \vec{F} \cdotp \vec{N} \ dS=\iiint _{D} Div(\vec{F}) \ dV
$$



