---
title: "Reading"
date: "2025-02-01"
categories: [Record, Workflow, Efficiency]
---

# 读什么
- **豆瓣(标记想读, 列书单), 微信读书**
- 知乎, B站, Youtube, 公众号等社交媒体推荐
- 淘宝
- 作者
- 问周围人
- 群友
- 搜索 xxx相关的书推荐, 关键词(豆瓣, Goodreads)
- Syllabus 课程书籍, 教材
- 高校培养方案
- **考研参考书籍**
- 其他书/网页/文章的参考/引用的书籍
- 按专业读, 按专题读, 按问题读

# 书源
- z-lib
- Anna's Archive
- 微信读书
- 搜索引擎
- **扫书群**
- 实体书
- 淘宝找书
- [国家哲学社会科学文献中心](https://www.ncpssd.cn/index) (中文论文/期刊)
    - 如: [社会学研究](https://www.ncpssd.cn/journal/details?gch=80772X)
- **中文电子书找不到可以找英文电子书读**

# 设备
- **一个把网卡拔掉的笔记本**
- **电纸书 e-ink**
- 手机
- 平板
- 电脑

# 软件
- **WPS PDF独立版**
  - **通过shell:startup设置开机自启动**
  - **Pin在Taskbar**
  - 批注 -> 形状批注
    - 下划线
    - 斜线: 关键词, 点, ...
    - 竖线, 竖线横线: 重要部分, 需要读完后截图
  - F11全屏 也可以 右键上边栏, uncheck 显示功能区
- 微信读书 
  - Pin Chrome Tab, 也可以开机自启 微信读书 App (by Chrome)
  - 移动设备放在首页或Docker栏
    - 放在只有一两个图标的首页中间偏右会比放在Docker好
- GoodNotes / NoteShelf
- **ReadEra: 可以切掉pdf的两边margin, 这样手机上读pdf会好很多**
- Calibre: 格式转换(ebook-convert, 2pdf脚本批量转换), epub, ...


# When
- 固定时间, 闹钟
- 不固定时间
- 事件时间
  - 等待
  - 在xx前
  - 在xx后
  - 通勤, 吃饭, 睡前
  - 游戏, 视频, 游戏与阅读并行
- 
- 整块时间
- 碎片时间: 碎片内容 如词典式，概念式，短篇, 论文, 不太重要的


# Where
- 固定地点: 书房, 图书馆, 车上, 车站
- Everywhere
- 
- 声音 降噪
- 通风
- 温度
- put phone away

# 习惯, 目标, 计划
- 微习惯, 微目标 
  - **daily 1 min/small action** 
- **想读就读(兴趣导向)** vs 读书计划/roadmap
- reading for an action (write, share, presentation, application, ...)
- 
- daily todo list
- project todo list
- reading plan and roadmap
- important dates
- 限时, 但允许一定超时


# 预处理 Pre-Process
- **看书评/读书笔记**
- **先快速翻过**
- **AI大纲/与AI聊聊, 这本书内容与有价值的问题**
- 先看相关论文
- 跟看过的人聊聊, 问问
- 问题
- 为什么读
- 

- 判断与预期: 
  - 书的类型，主题，主体，内容
  - 难度 
  - 偏离与调整
  - 需要花多少小时, 多少天, ...
  - 值得读吗?
  - 值得全文读吗? 还是选读?


# 读中 注意力
- 判断/归类/问题
  - 论点, 论证, 论据...
  - 定义/概念解释, 性质, 联系, 隐喻/类比, 问题
  - 知道 vs 不知道
  - 熟悉 vs 不熟悉
  - 能大概它要讲什么 vs 不能预测
  - **要跳过么?**
  - **要提速吗?** 
  - 要减速吗?
  - **和我之前读的/学的东西有什么关系/关联?**
  - **和问题相关吗? 有何种练习** (带着问题读, 问题赋予文本和段落不同的权重)
  - **和我如何练习?**
    - 什么场景?
- 

- 结构化, 编织/串联, 流程
  - 分类 分点 分层 分序 
  - 联系 类比 支持
  - 演绎 归纳 
- 

- 流式 
- 块式 
- 句式 
- 段式 
- 扫式（两条线）
- 笔或鼠标指针视觉引导, 不一定非是流式的视觉引导
- 

- **文档宽度不要太宽** 合适的缩放很重要
  - 视幅扩展
- 调整字体(不要太大), 行距, 边距
- **减少中断（比如划很多线, 添加后处理过程）**
  - 划很多线也是一种想着一次就掌握/吃下所有的表现
- **不要匀速**
- **不是同等重要的**
- **几本书切换着读 (最好不要超过3本)**
- **Catch Keywords and the relationship of keywords**
- **不要背书/考试思维**
- **不要想着一次就掌握/吃下所有**
- 水, 饮料, 零食
- 减少回读
- 看书 -> 听书 -> 看书 的接力
- 速度切换
- 焦点切换
- 番茄工作法(25-5, 40-10) (可选)

# 英语阅读速度需要刻意练习
- **刻意练习速度是指: 读时不要想着同时兼顾速度练习, 内容, 词汇, 愉悦...而是专注于练习速度和克服英文阅读的心理障碍**
- **练习的书籍不宜太难, 但要覆盖不同的类型**
- 练习的书籍需要一定程度的重复阅读 
- 必须克服英语考试式的阅读心理
  - 克服要都读懂
  - 克服每个单词都要认识的心理
  - 克服全都要读, 如果你留意的话你正常速度读中文绝对不是全读, 而是自动忽略了不少内容但是你察觉不到. 但是英文你会更容易察觉, 而你要做的自动忽略某些片段而不察觉/不自知
- 

- **忽略生词(除了重要词汇) until it repeats**
  - **边读边查的频率一定要降低**再降低
- **Bionic Reading**
  - **找到感觉后要撇开Bionic Reading的样式**
  - **在单词前几个字母跳动（流式）**
  - **Bionic流式不要贯穿全书, 而一定是和其他模式切换的**
- **流/块/句/几行/段/扫处理模式的切换**
- 判断句子成分
- 逻辑链接词
- 减少回读
- 注意力焦点跳转


# 后处理 Post-Process
- **PixPin -> LogSeq(Multiple Files into Assets Plugin) -> Anki** 
  - **不要想着一次做完, 可以看别的书不想看的时候切过来截图和写笔记**
- **写文章 -> 博客**
- **日总结, 月总结**
- **分享: 朋友 群 朋友圈**
- 展望, 还没解决的问题/不足, 接下来读什么
- 参考文献


# X
**读多想少 想多读少的辩证法**

是行动还是阅读